
stages:
  - build
  - test

linux-build:
  stage: build
  tags:
    - linux
  script:
    - premake5 gmake2
    - make -j4
  artifacts:
    paths:
      - bin/

build-windows:
  stage: build
  tags:
    - windows
  script:
    - premake5 vs2019
    - 'echo $Env:APPDATA'
    - '& "${Env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\amd64\msbuild.exe"'
  artifacts:
    paths:
      - bin/

documentation-job:
  stage: build
  script:
    - doxygen doc/Doxyfile
    # commented out because it fails the build due to missing permissions
    - rm -rf /mnt/doxygenDocu/gatery/*
    - mv doc/gen/html/ /mnt/doxygenDocu/gatery
  only:
    - master

test-linux-frontend:
  stage: test
  tags:
    - linux
  script:
    - cd build
    - frontend/unitTests/unitTestCore
  dependencies:
    - linux-build

test-linux-stl:
  stage: test
  tags:
    - linux
  script:
    - cd build
    - stl/unitTests/unitTestSTL
  dependencies:
    - linux-build

test-windows-frontend:
  stage: test
  tags:
    - windows
  script:
    - .\bin\windows-x86_64-Debug\gatery-frontend-test.exe
  dependencies:
    - build-windows

test-windows-stl:
  stage: test
  tags:
    - windows
  script:
    - .\bin\windows-x86_64-Debug\gatery-scl-test.exe
  dependencies:
    - build-windows

