
stages:
  - configure
  - build
  - test
  - deploy


configure-job-linux:
  stage: configure
  tags: 
    - linux
  script:
    - rm -Rf build
    - mkdir build
    - cd build
    - cmake ..
  artifacts:
    paths:
      - build/

configure-job-windows:
  stage: configure
  tags: 
    - windows
  script:
    - rm -Force -Recurse -ErrorAction Ignore .\build\
    - mkdir build
    - cd build
    - cmake ..
  artifacts:
    paths:
      - build/

build-job:
  stage: build
  script:
    - cd build
    - make -j 8
  dependencies:
    - configure-job-linux
  artifacts:
    paths:
      - build/

documentation-job:
  stage: configure
  script:
    - doxygen doc/Doxyfile
    # commented out because it fails the build due to missing permissions
    # - rm -rf /mnt/doxygenDocu/tech/doxygenDocu/gatery/*
    # - mv doc/gen/html/ /mnt/doxygenDocu/tech/doxygenDocu/gatery
  only:
    - master

test-job-frontend:
  stage: test
  script:
    - cd build
    - frontend/unitTests/unitTestCore
  dependencies:
    - build-job

test-job-stl:
  stage: test
  script:
    - cd build
    - stl/unitTests/unitTestSTL
  dependencies:
    - build-job

