
stages:
  - configure
  - build
  - test
  - deploy


configure-job:
  stage: configure
  script:
    - rm -Rf build
    - mkdir build
    - cd build
    - cmake .. > ./result.txt
  artifacts:
    paths:
      - build/
      - result.txt  

build-job:
  stage: build
  script:
    - cd build
    - make -j 8 >> ./result.txt
  dependencies:
    - configure-job
  artifacts:
    paths:
      - build/
      - result.txt  

build-job-documentation:
  stage: configure
  script:
    - doxygen doc/Doxyfile
  artifacts:
    paths:
      - doc/gen/

test-job-frontend:
  stage: test
  script:
    - cd build
    - frontend/unitTests/unitTestCore > test_frontend.txt
  dependencies:
    - build-job
  artifacts:
    paths:
      - test_frontend.txt  

test-job-stl:
  stage: test
  script:
    - cd build
    - stl/unitTests/unitTestSTL > test_STL.txt
  dependencies:
    - build-job
  artifacts:
    paths:
      - test_STL.txt  

