

build-job:
  stage: build
  script:
    - rm -Rf build
    - mkdir build
    - cd build
    - cmake ..
    - make -j 8

build-job-documentation:
  stage: build
  script:
    - echo TODO Build documentation


test-job-frontend:
  stage: test
  script:
    - cd build
    - frontend/unitTests/unitTestCore

test-job-stl:
  stage: test
  script:
    - cd build
    - stl/unitTests/unitTestSTL


