
stages:
  - configure
  - build
  - test
  - deploy


configure-job:
  stage: configure
  script:
    - rm -Rf build
    - mkdir build
    - cd build
    - cmake ..
  artifacts:
    paths:
      - build/

build-job:
  stage: build
  script:
    - cd build
    - make -j 8
  dependencies:
    - configure-job
  artifacts:
    paths:
      - build/

documentation-job:
  stage: configure
  script:
    - doxygen doc/Doxyfile
    - mv doc/gen/html/ /mnt/doxygenDocu/tech/doxygenDocu/
  only:
    - master

test-job-frontend:
  stage: test
  script:
    - cd build
    - frontend/unitTests/unitTestCore
  dependencies:
    - build-job

test-job-stl:
  stage: test
  script:
    - cd build
    - stl/unitTests/unitTestSTL
  dependencies:
    - build-job

