
stages:
  - configure
  - build
  - test
  - deploy


configure-job:
  stage: configure
  script:
    - rm -Rf build
    - mkdir build
    - cd build
    - cmake ..

build-job:
  stage: build
  script:
    - cd build
    - make -j 8

build-job-documentation:
  stage: build
  script:
    - echo TODO Build documentation

test-job-frontend:
  stage: test
  script:
    - cd build
    - frontend/unitTests/unitTestCore

test-job-stl:
  stage: test
  script:
    - cd build
    - stl/unitTests/unitTestSTL


