
stages:
  - build
  - test
  - deploy

linux-build-job:
  stage: build
  tags:
    - linux
  script:
    - rm -Rf build
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build . -j 4
  artifacts:
    paths:
      - build/

build-windows:
  stage: build
  tags:
    - windows
  script:
    - premake5 vs2019
    - '& "$${Env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\amd64\msbuild.exe"'
  artifacts:
    paths:
      - build/

documentation-job:
  stage: build
  script:
    - doxygen doc/Doxyfile
    # commented out because it fails the build due to missing permissions
    - rm -rf /mnt/doxygenDocu/gatery/*
    - mv doc/gen/html/ /mnt/doxygenDocu/gatery
  only:
    - master

test-linux-frontend:
  stage: test
  tags:
    - linux
  script:
    - cd build
    - frontend/unitTests/unitTestCore

test-linux-stl:
  stage: test
  tags:
    - linux
  script:
    - cd build
    - stl/unitTests/unitTestSTL

test-windows-frontend:
  stage: test
  tags:
    - windows
  script:
    - .\build\frontend\unitTests\Debug\unitTestCore.exe

test-windows-stl:
  stage: test
  tags:
    - windows
  script:
    - .\build\stl\unitTests\Debug\unitTestSTL.exe

