
stages:
  - configure
  - build
  - test
  - deploy


configure-job-linux:
  stage: configure
  tags: 
    - linux
  script:
    - rm -Rf build
    - mkdir build
    - cd build
    - cmake ..
  artifacts:
    paths:
      - build/

build-job-linux:
  stage: build
  tags:
    - linux
  script:
    - cd build
    - make -j 8
  dependencies:
    - configure-job-linux
  artifacts:
    paths:
      - build/

build-windows:
  stage: build
  tags:
    - windows
  script:
    - if(Test-Path .\build\) { rm -Force -Recurse .\build\ }
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=C:/gitlab-runner/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe"
    - cmake --build .
  artifacts:
    paths:
      - build/

documentation-job:
  stage: configure
  script:
    - doxygen doc/Doxyfile
    # commented out because it fails the build due to missing permissions
    # - rm -rf /mnt/doxygenDocu/tech/doxygenDocu/gatery/*
    # - mv doc/gen/html/ /mnt/doxygenDocu/tech/doxygenDocu/gatery
  only:
    - master

test-linux-frontend:
  stage: test
  tags:
    - linux
  script:
    - cd build
    - frontend/unitTests/unitTestCore

test-linux-stl:
  stage: test
  tags:
    - linux
  script:
    - cd build
    - stl/unitTests/unitTestSTL

test-windows-frontend:
  stage: test
  tags:
    - windows
  script:
    - .\build\frontend\unitTests\Debug\unitTestCore.exe

test-windows-stl:
  stage: test
  tags:
    - windows
  script:
    - .\build\stl\unitTests\Debug\unitTestSTL.exe

